// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID       string     `json:"id"`
	PostID   string     `json:"postId"`
	ParentID *string    `json:"parentId,omitempty"`
	Author   string     `json:"author"`
	Content  string     `json:"content"`
	Replies  []*Comment `json:"replies"`
}

type CommentPage struct {
	Comments []*Comment `json:"comments"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Author   string  `json:"author"`
	Content  string  `json:"content"`
}

type CreatePostInput struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	AllowComments bool   `json:"allowComments"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	Comments      []*Comment `json:"comments"`
	AllowComments bool       `json:"allowComments"`
}

type Query struct {
}

type UpdatePostInput struct {
	ID            string  `json:"id"`
	Title         *string `json:"title,omitempty"`
	Content       *string `json:"content,omitempty"`
	AllowComments *bool   `json:"allowComments,omitempty"`
}
